name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

env:
  APP_NAME: pocapps
  RESOURCE_GROUP: POC
  DOCKER_IMAGE: aavisantech1997/pocapps:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t $DOCKER_IMAGE .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $DOCKER_IMAGE \
            --docker-registry-server-url https://index.docker.io

      - name: Restart Azure Web App
        run: az webapp restart \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP
